name: CI
on:
  - push

permissions: {}
jobs:
  check-latest-versions:
    permissions:
      contents: read
    runs-on: "ubuntu-24.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make sure we don't build and can't publish
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: |
          echo "Error: This workflow should only run on version tags (refs/tags/v*)"
          exit 1
  #      - name: Check latest versions
  #        run: ./check-latest-versions.sh
  build:
    permissions:
      contents: read
    name: build-${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    needs: check-latest-versions
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu-24.04"
            platform: "linux-x64"
          # FIXME enable this back
          # - os: "ubuntu-24.04"
          #   platform: "linux-armv6"
          # - os: "ubuntu-24.04"
          #   platform: "win32-x64"
          # - os: "macos-15-intel"
          #   platform: "darwin-x64"
          # - os: "macos-15"
          #   platform: "darwin-arm64v8"
          # - os: "ubuntu-24.04-arm"
          #   platform: "linux-arm64v8"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          pipx install meson
          brew install automake nasm
      - name: Build ${{ matrix.platform }}
        run: ./build.sh ${{ matrix.platform }}
      - name: Upload ${{ matrix.platform }} artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}
          path: "*.tar.gz"
          compression-level: 0
          retention-days: 1
          if-no-files-found: error
  populate-and-publish-npm-workspace:
    permissions:
      contents: write
      id-token: write
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "24"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Populate npm workspace
        run: ./populate-npm-workspace.sh
      - name: Create npm workspace tarball
        run: ls -l && tar -vcaf npm-workspace.tar.xz -C npm .
      - name: Generate release notes
        run: ./generate-release-notes.sh
      - name: Package individual npm packages
        run: ./package-npm-packages.sh
      - name: Create GitHub release for tag
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.tar.*"
          artifactContentType: application/x-xz
          bodyFile: release-notes.md
          draft: true
          # prerelease: ${{ contains(github.ref, '-rc') }}
          # makeLatest: ${{ !contains(github.ref, '-rc') }}
      # - name: Publish npm packages
      #   if: startsWith(github.ref, 'refs/tags/v')
      #   run: cd npm && npm publish --workspaces --tag=${{ contains(github.ref, '-rc') && 'next' || 'latest' }}
